

spring.application.name=gerenciador-metas

spring.datasource.url=jdbc:mysql://localhost:3306/gerenciador_metas?useSSL=false&serverTimezone=America/Bahia&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=${SECRET_KEY:}
server.port=8080